// src/components/ImagePreview.vue
<script setup lang="ts">
defineProps<{
  imageUrl: string;
}>();
</script>

<template>
  <div class="image-preview">
    <img v-if="imageUrl" :src="imageUrl" alt="预览图片">
  </div>
</template>

<style scoped>
.image-preview {
  margin: 20px 0;
  max-width: 100%;
}

.image-preview img {
  max-width: 100%;
  max-height: 200px;
  border-radius: 8px;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}
</style>

// react-app/src/components/ImagePreview.tsx
import React from 'react';

interface ImagePreviewProps {
  imageUrl: string;
}

export const ImagePreview: React.FC<ImagePreviewProps> = ({ imageUrl }) => {
  if (!imageUrl) return null;

  return (
    <div className="mt-4">
      <div className="relative max-w-md mx-auto">
        <img
          src={imageUrl}
          alt="Preview"
          className="w-full h-auto rounded-lg shadow-md"
          style={{ maxHeight: '300px', objectFit: 'contain' }}
        />
      </div>
    </div>
  );
};
