// src/components/TextList.vue
<script setup lang="ts">
import { ElMessage, ElMessageBox } from 'element-plus'
import { to } from '@iceywu/utils'
import {
	A11y,
	Navigation,
	// Pagination,
	Scrollbar,
	Keyboard,
	Mousewheel,
} from 'swiper/modules'

// Import Swiper Vue.js components
import { Swiper, SwiperSlide } from 'swiper/vue'
import { deleteWords, getWordsList } from '@/api/words'

// Import Swiper styles
import 'swiper/css'
import 'swiper/css/navigation'
import 'swiper/css/pagination'
import 'swiper/css/scrollbar'
import 'swiper/css/mousewheel'
import 'swiper/css/keyboard'

const emit = defineEmits(['edit'])

// Import Swiper styles
// const onSwiper = (swiper) => {

// }
function onSlideChange() {

}

const modules = [Navigation, Scrollbar, A11y, Keyboard, Mousewheel]

const [DefineTemplate, ReuseTemplate] = createReusableTemplate()
interface DataItem {
	author?: string
	title?: string
	content: string
	bookName?: string
}
const dataList = ref<DataItem[]>([
	{
		content: `
		“这个爱情故事，好像是个悲剧？”<br />
		“你说的是婚姻，爱情没有悲剧。”<br />
		对爱者而言，爱情怎么会是悲剧？对春天而言，秋天是它的悲剧吗？<br />
		“结尾是什么？”<br />
		“等待。”<br />
		“之后呢？” <br />
		“没有之后” <br />
		“或者说，等待的结果呢？” <br />
		“等待就是结果。” <br />
		“那，不是悲剧吗？” <br />
		“不，是秋天” <br />
		`,
		author: '史铁生',
		book_name: '我与地坛',
	},
	{
		content: `
		我的心底锁着一封苍老的信等你来读时，<br />
		愿我仍年轻。
		`,
		author: '陈繁齐',
		book_name: '',
	},
	{
		content: `
		我想要偶尔想起你<br />
		偶尔疼痛<br />
		想起生命里曾经有一场相遇
		`,
		author: '陈繁齐',
		book_name: '',
	},
	{
		content: `
		如果你决定要来找我了<br />
		就请你带着足够爱我的容器<br />
		好让我把余生的温柔都盛给你
		`,
		author: '陈繁齐',
		book_name: '',
	},
])
function showName(data: DataItem) {
	const { author, book_name } = data
	const authorName = author || '佚名'
	const bookNameTemp = book_name ? `《${book_name}》` : ''
	return `${authorName} ${bookNameTemp}`
}
const navigation = {
	nextEl: '.swiper-button-next',
	prevEl: '.swiper-button-prev',
}
function nextEl() {

}
function prevEl(item: DataItem, index: number) {

}
function formatStringWithBr(str: string) {
	const punctuationRegex
		= /([，。！？；：“”‘’（）《》【】〈〉.!?;:"'()])/g
	return str.replace(punctuationRegex, (match) => {
		return `${match}<br />`
	})
}

// 🌈 接口数据请求
const getDataLoading = ref(false)
async function getWordsData() {
	if (getDataLoading.value)
return
	getDataLoading.value = true
	const params = {
		page: 1,
		size: 1000,
	}

	const [_, res] = await to(getWordsList(params))
	if (res) {
		const { code, result = {} } = res || {}
		if (code === 200 && result) {
			const { data = [] } = result || {}
			const tempData = data.map((item) => {
				return {
					...item,
					// content: formatStringWithBr(item.content),
					book_name: item.bookName,
					content: item.content.replace(/\n/g, '<br>'),
				}
			})

			dataList.value = tempData || []
		}
	}

	getDataLoading.value = false
}
function handleEdit(item, index) {
	emit('edit', item)
}
async function handleDelete(id: any, index) {
	ElMessageBox.confirm('确定删除改摘抄吗?', '提示', {
		confirmButtonText: '确定',
		cancelButtonText: '取消',
		type: 'warning',
	})
		.then(async () => {
			const [_, res] = await to(deleteWords(id))
			if (res) {
				const { code, result = [] } = res || {}
				if (code === 200) {
					dataList.value.splice(index, 1)
					ElMessage({
						type: 'success',
						message: '删除成功',
					})
				}
			}
		})
		.catch(() => {})
}
onMounted(() => {
	getWordsData()
})
defineExpose({
	getWordsData,
})
// const swiperRef = ref();
// const swiperActiveIndex = computed(() => {

// 	return swiperRef.value?.activeIndex
// })
</script>

<template>
	<div class="h-full w-full">
		<DefineTemplate v-slot="{ data }">
			<div class="base-font">
				<p class="text-xl line-height-10" v-html="data.content" />
				<p class="mt-5 text-end text-lg">——{{ showName(data) }}</p>
			</div>
		</DefineTemplate>
		<!-- 列表 -->
		<Swiper
			class="h-full"
			:modules="modules"
			:loop="true"
			:slides-per-view="1"
			:space-between="50"
			:autoplay="{ delay: 4000, disableOnInteraction: false }"
			:navigation="navigation"
			:pagination="{ clickable: true }"
			:scrollbar="{ draggable: false }"
			:keyboard="{ enabled: true }"
			:mousewheel="{ enabled: true }"
			direction="vertical"
			@slide-change="onSlideChange"
		>
			<SwiperSlide v-for="(item, index) in dataList" :key="index">
				<div class="fixed bottom-10 right-10 flex gap-5">
					<button
						class="flex select-none items-center gap-3 rounded-full bg-white p-3.5 text-center align-middle text-sm text-blue-gray-900 font-bold font-sans uppercase shadow-blue-gray-500/10 shadow-xl transition-all disabled:pointer-events-none active:opacity-[0.85] disabled:opacity-50 focus:opacity-[0.85] active:shadow-none disabled:shadow-none focus:shadow-none hover:shadow-blue-gray-500/20 hover:shadow-lg"
						type="button"
						@click="handleEdit(item, index)"
					>
						编辑
					</button>
					<button
						class="flex select-none items-center gap-3 rounded-full bg-white p-3.5 text-center align-middle text-sm text-blue-gray-900 font-bold font-sans uppercase shadow-blue-gray-500/10 shadow-xl transition-all disabled:pointer-events-none active:opacity-[0.85] disabled:opacity-50 focus:opacity-[0.85] active:shadow-none disabled:shadow-none focus:shadow-none hover:shadow-blue-gray-500/20 hover:shadow-lg"
						type="button"
						@click="handleDelete(item.id, index)"
					>
						删除
					</button>
				</div>

				<div class="box-border h-full w-full fcc px-13">
					<ReuseTemplate :data="item" />
				</div>
			</SwiperSlide>

			<div
				class="swiper-button-prev btn-icon !text-[#374151]"
				@click.stop="prevEl(item, index)"
			/>

			<!-- 左箭头。如果放置在swiper外面，需要自定义样式。 -->
			<div
				class="btn-icon swiper-button-next !text-[#374151]"
				@click.stop="nextEl"
			/>
		</Swiper>
		<div />
	</div>
</template>

<style scoped>
.read-the-docs {
  color: #888;
  font-size: 1.2rem;
  animation: slide-up 0.5s ease-out;
}

@keyframes slide-up {
  from {
    transform: translateY(20px);
    opacity: 0;
  }
  to {
    transform: translateY(0);
    opacity: 1;
  }
}

.base-font {
  font-family: 'SmileySansOblique';
  text-align: start;
}
.btn-icon {
  z-index: 99999;
  display: flex;
  justify-content: center;
  align-items: center;
  border-radius: 100%;
  width: 60px;
  height: 60px;
  border-radius: 50%;
  /* background: rgba(255, 255, 255, 0.4); */
  border: 1px solid rgba(0, 0, 0, 0.08);
  box-shadow:
    0 1px 2px rgba(0, 0, 0, 0.025),
    0 2px 8px rgba(0, 0, 0, 0.05);
  cursor: pointer;
  transition: all 0.3s;
  &:after {
    font-size: 25px !important;
  }
  &:hover {
    transform: scale(1.1);
  }
}
</style>

// react-app/src/components/TextList.tsx
import React, { useState, useEffect } from 'react';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation, Keyboard, Mousewheel } from 'swiper/modules';
import { Button } from '@/components/ui/button';
import { Edit, Trash2 } from 'lucide-react';
import { TextExcerpt } from '@/types';

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/navigation';

interface TextListProps {
  onEdit: (data: TextExcerpt) => void;
  onDelete: (id: number) => void;
}

export const TextList: React.FC<TextListProps> = ({ onEdit, onDelete }) => {
  const [excerpts, setExcerpts] = useState<TextExcerpt[]>([
    {
      id: 1,
      content: `"这个爱情故事，好像是个悲剧？"<br />
"你说的是婚姻，爱情没有悲剧。"<br />
对爱者而言，爱情怎么会是悲剧？对春天而言，秋天是它的悲剧吗？<br />
"结尾是什么？"<br />
"等待。"<br />
"之后呢？" <br />
"没有之后" <br />
"或者说，等待的结果呢？" <br />
"等待就是结果。" <br />
"那，不是悲剧吗？" <br />
"不，是秋天"`,
      author: '史铁生',
      bookName: '我与地坛',
    },
    {
      id: 2,
      content: `我的心底锁着一封苍老的信等你来读时，<br />
愿我仍年轻。`,
      author: '陈繁齐',
      bookName: '',
    },
    {
      id: 3,
      content: `我想要偶尔想起你<br />
偶尔疼痛<br />
想起生命里曾经有一场相遇`,
      author: '陈繁齐',
      bookName: '',
    },
    {
      id: 4,
      content: `如果你决定要来找我了<br />
就请你带着足够爱我的容器<br />
好让我把余生的温柔都盛给你`,
      author: '陈繁齐',
      bookName: '',
    },
  ]);

  const [currentExcerpt, setCurrentExcerpt] = useState<TextExcerpt>(excerpts[0]);

  const showName = (data: TextExcerpt) => {
    const authorName = data.author || '佚名';
    const bookName = data.bookName ? `《${data.bookName}》` : '';
    return `${authorName} ${bookName}`;
  };

  const handleSlideChange = (swiper: any) => {
    const currentIndex = swiper.realIndex;
    setCurrentExcerpt(excerpts[currentIndex]);
  };

  const handleEdit = () => {
    onEdit(currentExcerpt);
  };

  const handleDelete = () => {
    if (currentExcerpt.id && window.confirm('确定删除该摘抄吗？')) {
      onDelete(currentExcerpt.id);
      // Remove from local state
      setExcerpts(prev => prev.filter(item => item.id !== currentExcerpt.id));
    }
  };

  const modules = [Navigation, Keyboard, Mousewheel];

  const ExcerptCard: React.FC<{ data: TextExcerpt }> = ({ data }) => (
    <div className="base-bg">
      <div className="base-font note-book">
        <div className="note-book-cover" />
        <p dangerouslySetInnerHTML={{ __html: data.content }} />
        <p className="text-right mt-4">——{showName(data)}</p>
      </div>
    </div>
  );

  return (
    <div className="h-full w-full">
      <Swiper
        className="h-full"
        modules={modules}
        loop={true}
        slidesPerView={1}
        spaceBetween={50}
        navigation={{
          nextEl: '.swiper-button-next',
          prevEl: '.swiper-button-prev',
        }}
        keyboard={{ enabled: true }}
        mousewheel={{ enabled: true }}
        direction="vertical"
        onSlideChange={handleSlideChange}
      >
        {excerpts.map((item) => (
          <SwiperSlide key={item.id}>
            <div className="box-border h-full w-full flex items-center justify-center px-12 md:px-48">
              <ExcerptCard data={item} />
            </div>
          </SwiperSlide>
        ))}
      </Swiper>

      {/* Action buttons */}
      <div className="fixed bottom-10 right-10 z-50 flex gap-5">
        <Button
          onClick={handleEdit}
          className="flex items-center gap-3 rounded-full bg-white p-3.5 text-blue-gray-900 shadow-xl hover:shadow-lg"
          variant="outline"
        >
          <Edit className="h-4 w-4" />
          编辑
        </Button>
        <Button
          onClick={handleDelete}
          className="flex items-center gap-3 rounded-full bg-white p-3.5 text-blue-gray-900 shadow-xl hover:shadow-lg"
          variant="outline"
        >
          <Trash2 className="h-4 w-4" />
          删除
        </Button>
      </div>
    </div>
  );
};
